export const GET_DOGS = "GET_DOGS";
export const POST_DOGS = "POST_DOGS";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_DOG_ID = "GET_DOG_ID";
export const FILTER_TEMPERAMENTS = "FILTER_TEMPERAMENTS"
export const FILTER_BY_BREEDS="FILTER_BY_BREEDS"